# Generated by Django 4.1.2 on 2022-11-23 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petition', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='petition',
            name='photo_url',
            field=models.TextField(null=True),
        ),
    ]
