# Generated by Django 4.1.1 on 2022-12-12 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_alter_article_related_articles'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='bias',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='article',
            name='topic_id',
            field=models.TextField(default=None),
        ),
    ]
