# Generated by Django 4.1.4 on 2022-12-13 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_alter_article_related_articles'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='bias',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='topic_id',
            field=models.TextField(null=True),
        ),
    ]
