# Generated by Django 4.1.2 on 2022-12-13 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_article_bias_article_topic_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='like_users',
            field=models.TextField(default='', null=True),
        ),
    ]
