# Generated by Django 4.1.1 on 2022-11-23 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='nickname',
        ),
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='None', max_length=50, unique=True),
        ),
    ]
