# Generated by Django 4.1.2 on 2022-11-15 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quora_id', models.IntegerField()),
                ('author_id', models.IntegerField()),
                ('content', models.TextField()),
            ],
        ),
    ]

