# Generated by Django 4.1.2 on 2022-12-07 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quora', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quora',
            name='author_politicianId',
            field=models.IntegerField(null=True),
        ),
    ]
