# Generated by Django 4.1.2 on 2022-11-08 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Politician',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('birth_date', models.TextField()),
                ('job', models.TextField()),
                ('political_party', models.TextField()),
                ('election_precinct', models.TextField()),
                ('committee', models.TextField()),
                ('committees', models.TextField()),
                ('reelection', models.TextField()),
                ('election_units', models.TextField()),
                ('telephone_number', models.TextField()),
                ('email', models.TextField()),
                ('homepage', models.TextField()),
                ('career_summary', models.TextField()),
                ('mona_code', models.TextField()),
            ],
        ),
    ]
