# Generated by Django 4.1.2 on 2022-11-08 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('politician', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='politician',
            name='homepage',
        ),
    ]
