# Generated by Django 4.1.2 on 2022-11-20 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('politician', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='politician',
            name='image_src',
            field=models.TextField(blank=True, null=True),
        ),
    ]
