# Generated by Django 4.1.2 on 2022-11-08 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('politician', '0002_remove_politician_homepage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='politician',
            name='telephone_number',
        ),
    ]
