# Generated by Django 4.1.2 on 2022-11-24 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('politician', '0002_politician_image_src'),
    ]

    operations = [
        migrations.AddField(
            model_name='politician',
            name='proposals',
            field=models.TextField(blank=True, null=True),
        ),
    ]
