# Generated by Django 4.1.2 on 2022-11-08 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('politician', '0003_remove_politician_telephone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='politician',
            name='birth_date',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='politician',
            name='career_summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='politician',
            name='committee',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='politician',
            name='committees',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='politician',
            name='election_precinct',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='politician',
            name='election_units',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='politician',
            name='email',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='politician',
            name='job',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='politician',
            name='mona_code',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='politician',
            name='name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='politician',
            name='political_party',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='politician',
            name='reelection',
            field=models.TextField(blank=True, null=True),
        ),
    ]
