# Generated by Django 4.1.2 on 2022-12-19 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('politician', '0003_politician_proposals'),
    ]

    operations = [
        migrations.AddField(
            model_name='politician',
            name='like_users',
            field=models.TextField(default='', null=True),
        ),
    ]
